// Generated by Supabase CLI
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      affiliates: {
        Row: {
          id: string
          tenant_id: string
          user_id: string
          referral_code: string
          current_tier_id: string | null
          parent_affiliate_id: string | null
          company_name: string | null
          website_url: string | null
          social_media: Json
          tax_id: string | null
          tax_form_type: string | null
          payment_threshold: number
          preferred_currency: string
          promotional_methods: string[]
          status: string
          approved_by: string | null
          approved_at: string | null
        }
        Insert: {
          id?: string
          tenant_id: string
          user_id: string
          referral_code: string
          current_tier_id?: string | null
          parent_affiliate_id?: string | null
          company_name?: string | null
          website_url?: string | null
          social_media?: Json
          tax_id?: string | null
          tax_form_type?: string | null
          payment_threshold?: number
          preferred_currency?: string
          promotional_methods?: string[]
          status?: string
          approved_by?: string | null
          approved_at?: string | null
        }
        Update: {
          id?: string
          tenant_id?: string
          user_id?: string
          referral_code?: string
          current_tier_id?: string | null
          parent_affiliate_id?: string | null
          company_name?: string | null
          website_url?: string | null
          social_media?: Json
          tax_id?: string | null
          tax_form_type?: string | null
          payment_threshold?: number
          preferred_currency?: string
          promotional_methods?: string[]
          status?: string
          approved_by?: string | null
          approved_at?: string | null
        }
      }
      tracking_links: {
        Row: {
          id: string
          tenant_id: string
          affiliate_id: string
          destination_url: string
          campaign_name: string
          utm_source: string
          utm_medium: string
          utm_campaign: string | null
          utm_content: string | null
          utm_term: string | null
          short_code: string
          qr_code_url: string | null
          status: string
          expires_at: string | null
          click_count: number
          conversion_count: number
          created_at: string
        }
        Insert: {
          id?: string
          tenant_id: string
          affiliate_id: string
          destination_url: string
          campaign_name: string
          utm_source: string
          utm_medium: string
          utm_campaign?: string | null
          utm_content?: string | null
          utm_term?: string | null
          short_code: string
          qr_code_url?: string | null
          status?: string
          expires_at?: string | null
          click_count?: number
          conversion_count?: number
          created_at?: string
        }
        Update: {
          id?: string
          tenant_id?: string
          affiliate_id?: string
          destination_url?: string
          campaign_name?: string
          utm_source?: string
          utm_medium?: string
          utm_campaign?: string | null
          utm_content?: string | null
          utm_term?: string | null
          short_code?: string
          qr_code_url?: string | null
          status?: string
          expires_at?: string | null
          click_count?: number
          conversion_count?: number
          created_at?: string
        }
      }
    }
  }
}